apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: three-tier
type: Opaque
stringData:
  MONGO_CONN_STR: "mongodb://<user>:<password>@<mongo-host>:27017/tasks?authSource=admin"
