apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 970460117753.dkr.ecr.us-east-1.amazonaws.com/backend-app:0d04eee7fbd300af99b7c86d8cbe9adbba7a4296
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_CONN_STR
          readinessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"